AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ENV:
    Type: String
    Default: dev
Resources:
  MySimpleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://chase-deployment-artifacts/ea3666295baa1bae0702492baf61862d
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: nodejs14.x
      Timeout: 30
      Events:
        RootEndpoint:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId:
              Ref: SimpleApiGateway
        ProxyEndpoint:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId:
              Ref: SimpleApiGateway
  Bucket:
    Type: AWS::S3::Bucket
  SimpleApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Variables:
        ServerlessExpressLambdaFunctionName:
          Ref: MySimpleFunction
  ApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - MySimpleFunction
        - Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ':'
          - Ref: AWS::AccountId
          - ':'
          - Ref: SimpleApiGateway
          - /*
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Join:
        - '-'
        - - hello-world-api
          - Ref: AWS::Region
          - Ref: ENV
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
Outputs:
  LambdaFunctionConsoleUrl:
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: AWS::Region
        - .console.aws.amazon.com/lambda/home?region=
        - Ref: AWS::Region
        - '#/functions/'
        - Ref: MySimpleFunction
  SimpleApiGatewayConsoleUrl:
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: AWS::Region
        - .console.aws.amazon.com/apigateway/home?region=
        - Ref: AWS::Region
        - '#/apis/'
        - Ref: SimpleApiGateway
        - /stages
  ApiUrl:
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: SimpleApiGateway
        - .execute-api
        - Ref: AWS::Region
        - .amazonaws.com
