AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ENV:
    Type: String
    Default: dev

Resources:
  MySimpleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs14.x
      Timeout: 30
      Events:
        RootEndpoint:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref SimpleApiGateway
        ProxyEndpoint:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref SimpleApiGateway
  Bucket:
    Type: AWS::S3::Bucket

  SimpleApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Variables:
        ServerlessExpressLambdaFunctionName: !Ref MySimpleFunction

  ApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt MySimpleFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ':'
          - !Ref AWS::AccountId
          - ':'
          - !Ref SimpleApiGateway
          - '/*'

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', ['hello-world-api', !Ref 'AWS::Region', !Ref ENV]]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: '/'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

Outputs:
  LambdaFunctionConsoleUrl:
    Value: !Join
      - ''
      - - https://
        - !Ref AWS::Region
        - '.console.aws.amazon.com/lambda/home?region='
        - !Ref AWS::Region
        - '#/functions/'
        - !Ref MySimpleFunction

  # Sets the URL which will be targeted when testing the API gateway via the console
  SimpleApiGatewayConsoleUrl:
    Value: !Join
      - ''
      - - https://
        - !Ref AWS::Region
        - '.console.aws.amazon.com/apigateway/home?region='
        - !Ref AWS::Region
        - '#/apis/'
        - !Ref SimpleApiGateway
        - '/stages'

  # Sets the URL from which the API can be remotely invoked (for example when using Postman)
  ApiUrl:
    Value: !Join
      - ''
      - - https://
        - !Ref SimpleApiGateway
        - '.execute-api'
        - !Ref AWS::Region
        - '.amazonaws.com'
